<?php
/** @var $block Grasch\HCaptcha\Block\HCaptcha */
$config = $block->getCaptchaUiConfig();
$renderingOptions = $config['rendering'] ?? [];
$isInvisible = !empty($config['invisible']);
?>
<div class="admin__field <?= /* @noEscape */ $isInvisible ? 'field-invisible-hcaptcha' : 'field-hcaptcha' ?>">
    <div id="admin-hcaptcha"
         class="admin-hcaptcha-content<?=
         /* @noEscape */ !empty($renderingOptions['size']) ? ' size-' . $renderingOptions['size'] : '' ?>"></div>
</div>

<script>
    require([
        'jquery'
    ], function (
        $
    ) {
        const element = document.createElement('script');
        const scriptTag = document.getElementsByTagName('script')[0];

        element.async = true;
        element.src = 'https://js.hcaptcha.com/1/api.js' +
            '?onload=globalOnHCaptchaOnLoadCallback&render=explicit&recaptchacompat=off';

        window.globalOnHCaptchaOnLoadCallback = function () {
            let token = '';

            this.widgetId = hcaptcha.render('admin-hcaptcha', {
                <?php foreach ($renderingOptions as $key => $value): ?>
                '<?= $block->escapeJs($key) ?>': '<?= $block->escapeJs($value) ?>',
                <?php endforeach; ?>
                'callback': function (token) { // jscs:ignore jsDoc
                    <?php if ($isInvisible): ?>
                    this.token = token;
                    $('#login-form').submit();
                    <?php endif; ?>
                }.bind(this)
            });

            <?php if ($isInvisible): ?>
            $('#login-form').submit(function (event) {
                if (!this.token) {
                    event.preventDefault(event);
                    event.stopImmediatePropagation();
                    hcaptcha.execute(this.widgetId);
                }
            }.bind(this));
            <?php endif; ?>
        }.bind(this);

        scriptTag.parentNode.insertBefore(element, scriptTag);
    });
</script>
